--
-- PostgreSQL database dump
--

-- Dumped from database version 16.2
-- Dumped by pg_dump version 16.2

-- Started on 2024-11-25 22:05:30

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- TOC entry 217 (class 1259 OID 16732)
-- Name: AccessRules; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."AccessRules" (
    "Id" integer NOT NULL,
    "ServiceName" text NOT NULL,
    "MaxRequests" integer NOT NULL
);


ALTER TABLE public."AccessRules" OWNER TO postgres;

--
-- TOC entry 216 (class 1259 OID 16731)
-- Name: AccessRules_Id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."AccessRules" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."AccessRules_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 215 (class 1259 OID 16726)
-- Name: __EFMigrationsHistory; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL
);


ALTER TABLE public."__EFMigrationsHistory" OWNER TO postgres;

--
-- TOC entry 4787 (class 0 OID 16732)
-- Dependencies: 217
-- Data for Name: AccessRules; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."AccessRules" ("Id", "ServiceName", "MaxRequests") FROM stdin;
2	A01_ZIS_WGS84	500
1	A06_ATE_TE_WGS84	800
3	C01_Belarus_WGS84	300
4	A05_EGRNI_WGS84	1000
\.


--
-- TOC entry 4785 (class 0 OID 16726)
-- Dependencies: 215
-- Data for Name: __EFMigrationsHistory; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."__EFMigrationsHistory" ("MigrationId", "ProductVersion") FROM stdin;
20241124205400_Initial	9.0.0
\.


--
-- TOC entry 4793 (class 0 OID 0)
-- Dependencies: 216
-- Name: AccessRules_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."AccessRules_Id_seq"', 4, true);


--
-- TOC entry 4641 (class 2606 OID 16738)
-- Name: AccessRules PK_AccessRules; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."AccessRules"
    ADD CONSTRAINT "PK_AccessRules" PRIMARY KEY ("Id");


--
-- TOC entry 4639 (class 2606 OID 16730)
-- Name: __EFMigrationsHistory PK___EFMigrationsHistory; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."__EFMigrationsHistory"
    ADD CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId");


-- Completed on 2024-11-25 22:05:30

--
-- PostgreSQL database dump complete
--

